### ISSUE TITLE
服务器异常无法连接

### ISSUE THREAD

**Issue by vistal8** [cooscode/serv00-singbox#1]
服务器异常无法连接

**Comment by JunLeB** [comment]
S11

**Comment by cooscode** [comment]
> 服务器异常无法连接

请看[TUTOR](https://github.com/cooscode/serv00-singbox/blob/main/TUTORIAL.md)，查看是否配置有问题，我使用完全没有问题，并且建议使用[TUTOR](https://github.com/cooscode/serv00-singbox/blob/main/TUTORIAL.md)中的推荐的节点方案。

**Comment by cooscode** [comment]
> 服务器异常无法连接

If you have any questions, please reply on time. If there is no response, The issue will be closed automatically in a week.
